package com.wujunshen.tinyurl.entity;

import java.util.Date;

import lombok.Data;

@Data
public class UrlMapping {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * tb_url_mapping.url_id
   *
   * @mbg.generated Fri May 01 16:18:13 CST 2020
   */
  private Long urlId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * tb_url_mapping.origin_url
   *
   * @mbg.generated Fri May 01 16:18:13 CST 2020
   */
  private String originUrl;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * tb_url_mapping.origin_url_md5
   *
   * @mbg.generated Fri May 01 16:18:13 CST 2020
   */
  private String originUrlMd5;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * tb_url_mapping.tiny_url
   *
   * @mbg.generated Fri May 01 16:18:13 CST 2020
   */
  private String tinyUrl;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * tb_url_mapping.url_type
   *
   * @mbg.generated Fri May 01 16:18:13 CST 2020
   */
  private int urlType;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * tb_url_mapping.create_time
   *
   * @mbg.generated Fri May 01 16:18:13 CST 2020
   */
  private Date createTime;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * tb_url_mapping.update_time
   *
   * @mbg.generated Fri May 01 16:18:13 CST 2020
   */
  private Date updateTime;
}
